### ISSUE TITLE
Clone Linode?

### ISSUE THREAD

**Issue by GeorgeWillaman** [RobinJ1995/linode-api-node#3]
Hey,
Does this offer support for cloning linodes, or is that something that we'll have to program in ourselves?
Thanks,
-George :)

**Comment by RobinJ1995** [comment]
If it's possible with the Linode API, then yes. Otherwise, no. This library is just a wrapper around Linode's own API.

**Comment by RobinJ1995** [comment]
https://developers.linode.com/api/v4/linode-instances-linode-id-clone/#post

So to call this API endpoint, you would use the `createLinodeInstanceClone` method.
